site_name: Wiki Libertin


nav:
  - Accueil: index.md
  - Premice: premice.md
  - Guide:
      - Installation: guide/installation.md
      - Utilisation: guide/utilisation.md
  - Lexique:
      - Lexique: Lexique/lexique.md
      - ABC: Lexique/pratique.md

  - Accesoire:
      - Accesoire soft: Accessoire/soft.md
      - Accesoire hard: Accessoire/hard.md
  - Club:
      - Tester: Club/tester.md
      - A tester: Club/a_tester.md


theme:
  language: fr
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  logo: img/logo/vanille.png
  favicon: img/logo/favicon-96x96.png


extra:
  generator: false

copyright: Copyright &copy; 2025 - 2025 Aza