name: Deploiement sur LWS
on:
  push:
    branches:
      - main # Branche utilisée pour le miroir LWS
jobs:
  web-deploy:
    name: Sync files via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository content
        uses: actions/checkout@v4
      - name: Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./kinklist.azarothis.fr/ # Répertoire racine du site sur LWS
